kind: "DeploymentConfig"
apiVersion: "v1"
metadata:
  name: "winoperator"
spec:
  template: 
    metadata:
      labels:
        name: "winoperator"
    spec:
      containers:
        - name: "winoperator"
          image: "glennswest/winoperator"
          ports:
            - containerPort: 8080
              protocol: "TCP"
  replicas: 1 
